### ISSUE TITLE
Light/Dark mode toggle button

### ISSUE THREAD

**Issue by theashu02** [BrunoLagoa/sidebar-menu#4]
@BrunoLagoa kindly assign me this under hacktoberfest 2022

**Comment by BrunoLagoa** [comment]
If possible help me with a star.

**Comment by theashu02** [comment]
@BrunoLagoa kindly review my PR #5 
![Screenshot (10)](https://user-images.githubusercontent.com/100701424/194505679-21885c12-cd30-44c6-a441-9a2ba53d393a.png)
![Screenshot (11)](https://user-images.githubusercontent.com/100701424/194505687-8040dc2e-a524-4a05-a9ed-0e6fb97dd00d.png)

**Comment by lordashuchauhan** [comment]
> If possible help me with a star.

Sir i am already stared the repository when you assign me.

**Comment by theashu02** [comment]
@BrunoLagoa  I already stared the repository, kindly review my PR #5 under Hacktoberfest 2022
